#ifndef __PILOTNET_MODEL_DATA_H__
#define __PILOTNET_MODEL_DATA_H__

//this file is generated by tflite2c.py

#include <stdint.h>
extern const unsigned char g_pilotnet_model_data[];
extern const unsigned int g_pilotnet_model_data_len;

#endif
